/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package automation_shopdeck;

import java.util.*;

public class Backbaseprob1 {

    public static Map<String, Integer> sum(int[] arr) {

        Map<String, Integer> mp = new HashMap<>();

        int oddsum = 0;
        int evensum = 0;

        for (int i = 0; i < arr.length; i++) {

            if (arr[i] % 2 == 0) {
                evensum += arr[i];
            } else {
                oddsum += arr[i];
            }
        }

        mp.put("oddsum", oddsum);
        mp.put("evensum", evensum);
        return mp;

    }

}
